language: python
sudo: false
deploy:
  provider: pypi
  user: arokem
  password:
    secure: VbYSkQEsViURCpHo2+uLszaWF0O0xN30DCLvnPxYdEFruOu87KIK7gzha3yCtq21OqamqnDwa+TB7cMJcnKnuHJR1/mTGynN8SyPo7QmwktfV/C7kq8F0QkL3sfuOJBHEtV0yXHU6kJ9DRTq9X7gqCm/r0NVnsnMqnYInnsadRM=
  on:
    tags: true
    repo: cni/MRS
    all_branches: true
script:
- true
